name: Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: doc
        root_file: cleanthesis-doc.tex
    - name: Archive cleanthesis-doc.pdf
      uses: actions/upload-artifact@v2
      with:
        name: cleanthesis-doc.pdf
        path: doc/cleanthesis-doc.pdf
